resources:
- name: ci-src
  type: git
  source:
    uri: https://github.com/sursmobil/concourse-pipelines.git

- name: src-dev
  type: git
  source:
    uri: https://github.com/sursmobil/dac.git
    branch: dev
    username: ((github-user))
    password: ((github-pass))

- name: src-stable
  type: git
  source:
    uri: https://github.com/sursmobil/dac.git
    branch: master
    username: ((github-user))
    password: ((github-pass))

jobs:
- name: unit-test
  plan:
    - aggregate:
      - get: ci-src
      - get: src-dev
        trigger: true
    - task: unit-test
      file: ci-src/tasks/erl-lib-unit-test.yml

- name: release
  plan:
  - aggregate:
    - get: ci-src
    - get: src-dev
      trigger: true
      passed: [unit-test]
  - task: unit-test
    file: ci-src/tasks/promote-to-master.yml
  - put: src-stable
    params:
      repository: src-dev
      merge: true
