resources:
- name: ci-src
  type: git
  source:
    uri: https://github.com/sursmobil/concourse-pipelines.git

- name: src-dev
  type: git
  source:
    uri: https://github.com/sursmobil/dac.git
    branch: dev

- name: src-stable
  type: git
  source:
    uri: https://github.com/sursmobil/dac.git
    banch: master
    username: ((github-user))
    password: ((github-pass))

jobs:
- name: dac-release
  plan:
  - aggregate:
    - get: ci-src
    - get: src-stable
    - get: src-dev
      trigger: true
  - task: unit-test
    file: ci-src/tasks/erl-lib-unit-test.yml
  - task: promote-to-master
    file: ci-src/tasks/promote-to-master.yml
  - put: src-stable
    params:
      rebase: true
